/** Auto-generated by scripts/import-metro-plan.js — do not edit by hand. */

export function metroPlanStationsGeoJson(): GeoJSON.FeatureCollection {
  return {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "fid": "2",
        "name": "Củ Chi",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến số 2",
        "route": "Bến xe Tây Ninh - Thủ Thiêm"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.5007782,
          10.9681571
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "2",
        "name": "Bền xe An Sương",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến số 2",
        "route": "Bến xe Tây Ninh - Thủ Thiêm"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.61374708922,
          10.843951333484
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "2",
        "name": "Tân Thới Nhất",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến số 2",
        "route": "Bến xe Tây Ninh - Thủ Thiêm"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6205742,
          10.8330821
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "2",
        "name": "Tân Bình",
        "description": "AKA Tham Lương",
        "color": "#00A0E2",
        "line": "Tuyến số 2",
        "route": "Bến xe Tây Ninh - Thủ Thiêm"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6279837,
          10.8245397
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "2",
        "name": "Phạm Văn Bách",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến số 2",
        "route": "Bến xe Tây Ninh - Thủ Thiêm"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6323352,
          10.8131574
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "2",
        "name": "Bà Quẹo",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến số 2",
        "route": "Bến xe Tây Ninh - Thủ Thiêm"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6359455,
          10.8023659
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "2",
        "name": "Nguyễn Hồng Đào",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến số 2",
        "route": "Bến xe Tây Ninh - Thủ Thiêm"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6439224,
          10.79736
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "2",
        "name": "Bảy Hiền",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến số 2",
        "route": "Bến xe Tây Ninh - Thủ Thiêm"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6528165,
          10.7928809
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "2",
        "name": "Phạm Văn Hai",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến số 2",
        "route": "Bến xe Tây Ninh - Thủ Thiêm"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.66075009708,
          10.789182879604
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "2",
        "name": "Công Viên Lê Thị Riêng",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến số 2",
        "route": "Bến xe Tây Ninh - Thủ Thiêm"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6646719,
          10.7864731
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "2",
        "name": "Hòa Hưng",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến số 2",
        "route": "Bến xe Tây Ninh - Thủ Thiêm"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.67692324843,
          10.780209861107
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "2",
        "name": "Dân Chủ",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến số 2",
        "route": "Bến xe Tây Ninh - Thủ Thiêm"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.68174958995,
          10.777966406472
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "2",
        "name": "Tao Đàn",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến số 2",
        "route": "Bến xe Tây Ninh - Thủ Thiêm"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.69089297697,
          10.773068070437
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "2",
        "name": "chợ Bến Thành",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến số 2",
        "route": "Bến xe Tây Ninh - Thủ Thiêm"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6984516,
          10.7714595
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "2",
        "name": "Nguyễn Huệ",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến số 2",
        "route": "Bến xe Tây Ninh - Thủ Thiêm"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.70598378653,
          10.772037462843
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "2",
        "name": "quảng trường thủ thiêm",
        "description": "quảng trường thủ thiêm",
        "color": "#00A0E2",
        "line": "Tuyến số 2",
        "route": "Bến xe Tây Ninh - Thủ Thiêm"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.71046435492,
          10.770756754735
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "2",
        "name": "Mai Chí Thọ",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến số 2",
        "route": "Bến xe Tây Ninh - Thủ Thiêm"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.71961301784,
          10.772631706697
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "2",
        "name": "Trần Não",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến số 2",
        "route": "Bến xe Tây Ninh - Thủ Thiêm"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.72730922135,
          10.776273771825
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "2",
        "name": "Bình Khánh",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến số 2",
        "route": "Bến xe Tây Ninh - Thủ Thiêm"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7375099,
          10.7816882
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "2",
        "name": "Ga Thủ Thiêm",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến số 2",
        "route": "Bến xe Tây Ninh - Thủ Thiêm"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7494974018,
          10.787948726621
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "3",
        "name": "Cộng Hòa",
        "description": "",
        "color": "#F9A01B",
        "line": "Tuyến số 3B",
        "route": "Ngã 6 Cộng Hòa - Hiệp Bình Phước"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6816449,
          10.7654571
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "3",
        "name": "Tao Đàn",
        "description": "",
        "color": "#F9A01B",
        "line": "Tuyến số 3B",
        "route": "Ngã 6 Cộng Hòa - Hiệp Bình Phước"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.69096944026,
          10.773041403062
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "3",
        "name": "Dinh Độc Lập",
        "description": "",
        "color": "#F9A01B",
        "line": "Tuyến số 3B",
        "route": "Ngã 6 Cộng Hòa - Hiệp Bình Phước"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.694423,
          10.7786001
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "3",
        "name": "Hồ Con Rùa",
        "description": "",
        "color": "#F9A01B",
        "line": "Tuyến số 3B",
        "route": "Ngã 6 Cộng Hòa - Hiệp Bình Phước"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6968377,
          10.7819336
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "3",
        "name": "Hoa Lư",
        "description": "",
        "color": "#F9A01B",
        "line": "Tuyến số 3B",
        "route": "Ngã 6 Cộng Hòa - Hiệp Bình Phước"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7016757,
          10.7869368
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "3",
        "name": "Công viên Sở Thú",
        "description": "",
        "color": "#F9A01B",
        "line": "Tuyến số 3B",
        "route": "Ngã 6 Cộng Hòa - Hiệp Bình Phước"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.70497252826,
          10.789995113699
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "3",
        "name": "Nguyễn Cửu Vân",
        "description": "",
        "color": "#F9A01B",
        "line": "Tuyến số 3B",
        "route": "Ngã 6 Cộng Hòa - Hiệp Bình Phước"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7095399,
          10.794662
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "3",
        "name": "Hàng Xanh",
        "description": "",
        "color": "#F9A01B",
        "line": "Tuyến số 3B",
        "route": "Ngã 6 Cộng Hòa - Hiệp Bình Phước"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7115355,
          10.8011223
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "3",
        "name": "Xô Viết Nghệ Tĩnh",
        "description": "",
        "color": "#F9A01B",
        "line": "Tuyến số 3B",
        "route": "Ngã 6 Cộng Hòa - Hiệp Bình Phước"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7119646,
          10.8096692
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "3",
        "name": "Bình Triệu",
        "description": "",
        "color": "#F9A01B",
        "line": "Tuyến số 3B",
        "route": "Ngã 6 Cộng Hòa - Hiệp Bình Phước"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7147219,
          10.8267094
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "3",
        "name": "Hiệp Bình Phước",
        "description": "",
        "color": "#F9A01B",
        "line": "Tuyến số 3B",
        "route": "Ngã 6 Cộng Hòa - Hiệp Bình Phước"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7191422,
          10.84868
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "3",
        "name": "Tam Bình",
        "description": "",
        "color": "#F9A01B",
        "line": "Tuyến số 3B",
        "route": "Ngã 6 Cộng Hòa - Hiệp Bình Phước"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7293454,
          10.8662659
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "3",
        "name": "Ga Sóng Thần",
        "description": "",
        "color": "#F9A01B",
        "line": "Tuyến số 3B",
        "route": "Ngã 6 Cộng Hòa - Hiệp Bình Phước"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7510819,
          10.8773711
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "3",
        "name": "Dĩ An",
        "description": "",
        "color": "#F9A01B",
        "line": "Tuyến số 3B",
        "route": "Ngã 6 Cộng Hòa - Hiệp Bình Phước"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7602444,
          10.895598
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "3",
        "name": "Ga Dĩ An",
        "description": "",
        "color": "#F9A01B",
        "line": "Tuyến số 3B",
        "route": "Ngã 6 Cộng Hòa - Hiệp Bình Phước"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7688918,
          10.9076924
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "4",
        "name": "Thuận An",
        "description": "",
        "color": "#00A651",
        "line": "Tuyến số 4",
        "route": "Thạnh Xuân - Đại Lộ Nguyễn Văn Linh"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.71167,
          10.9302095
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "4",
        "name": "Thạnh Xuân",
        "description": "",
        "color": "#00A651",
        "line": "Tuyến số 4",
        "route": "Thạnh Xuân - Đại Lộ Nguyễn Văn Linh"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6665559503,
          10.874368377296
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "4",
        "name": "Ngã Tư Ga",
        "description": "",
        "color": "#00A651",
        "line": "Tuyến số 4",
        "route": "Thạnh Xuân - Đại Lộ Nguyễn Văn Linh"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6796262,
          10.8620928
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "4",
        "name": "Cầu An Lộc",
        "description": "",
        "color": "#00A651",
        "line": "Tuyến số 4",
        "route": "Thạnh Xuân - Đại Lộ Nguyễn Văn Linh"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6782332,
          10.8498075
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "4",
        "name": "An Nhơn",
        "description": "",
        "color": "#00A651",
        "line": "Tuyến số 4",
        "route": "Thạnh Xuân - Đại Lộ Nguyễn Văn Linh"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6769242,
          10.8436538
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "4",
        "name": "Nguyễn Văn Lương",
        "description": "",
        "color": "#00A651",
        "line": "Tuyến số 4",
        "route": "Thạnh Xuân - Đại Lộ Nguyễn Văn Linh"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.676023,
          10.8388909
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "4",
        "name": "Ngã 6 Gò Vấp",
        "description": "",
        "color": "#00A651",
        "line": "Tuyến số 4",
        "route": "Thạnh Xuân - Đại Lộ Nguyễn Văn Linh"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6793275,
          10.8270887
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "4",
        "name": "Bệnh viện 175",
        "description": "",
        "color": "#00A651",
        "line": "Tuyến số 4",
        "route": "Thạnh Xuân - Đại Lộ Nguyễn Văn Linh"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6790485,
          10.817752
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "4",
        "name": "Công Viện Gia Định",
        "description": "",
        "color": "#00A651",
        "line": "Tuyến số 4",
        "route": "Thạnh Xuân - Đại Lộ Nguyễn Văn Linh"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6778255,
          10.8099116
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "4",
        "name": "Ngã 4 Phú Nhuận",
        "description": "",
        "color": "#00A651",
        "line": "Tuyến số 4",
        "route": "Thạnh Xuân - Đại Lộ Nguyễn Văn Linh"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6797352,
          10.7995204
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "4",
        "name": "Cầu Kiệu",
        "description": "",
        "color": "#00A651",
        "line": "Tuyến số 4",
        "route": "Thạnh Xuân - Đại Lộ Nguyễn Văn Linh"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6852069,
          10.7928177
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "4",
        "name": "Lê Văn Tám",
        "description": "",
        "color": "#00A651",
        "line": "Tuyến số 4",
        "route": "Thạnh Xuân - Đại Lộ Nguyễn Văn Linh"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6923523,
          10.7879275
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "4",
        "name": "Hồ Con Rùa",
        "description": "",
        "color": "#00A651",
        "line": "Tuyến số 4",
        "route": "Thạnh Xuân - Đại Lộ Nguyễn Văn Linh"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6968838316,
          10.782067089955
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "4",
        "name": "Nhà Hát Sài Gòn",
        "description": "",
        "color": "#00A651",
        "line": "Tuyến số 4",
        "route": "Thạnh Xuân - Đại Lộ Nguyễn Văn Linh"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7022228,
          10.7762498
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "4",
        "name": "chợ Bến Thành",
        "description": "",
        "color": "#00A651",
        "line": "Tuyến số 4",
        "route": "Thạnh Xuân - Đại Lộ Nguyễn Văn Linh"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6983846,
          10.7715122
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "4",
        "name": "Hoàng Diệu",
        "description": "",
        "color": "#00A651",
        "line": "Tuyến số 4",
        "route": "Thạnh Xuân - Đại Lộ Nguyễn Văn Linh"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.70135284594,
          10.761422786915
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "4",
        "name": "Tôn Đản",
        "description": "",
        "color": "#00A651",
        "line": "Tuyến số 4",
        "route": "Thạnh Xuân - Đại Lộ Nguyễn Văn Linh"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.70528912697,
          10.753407682302
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "4",
        "name": "Nguyễn Thị Thập",
        "description": "",
        "color": "#00A651",
        "line": "Tuyến số 4",
        "route": "Thạnh Xuân - Đại Lộ Nguyễn Văn Linh"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.70113209192,
          10.740042438159
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "4",
        "name": "Nguyễn Văn Linh",
        "description": "PMY TAY",
        "color": "#00A651",
        "line": "Tuyến số 4",
        "route": "Thạnh Xuân - Đại Lộ Nguyễn Văn Linh"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.69979,
          10.7275643
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "4",
        "name": "Phước Kiển",
        "description": "",
        "color": "#00A651",
        "line": "Tuyến số 4",
        "route": "Thạnh Xuân - Đại Lộ Nguyễn Văn Linh"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7067825,
          10.7087571
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "4",
        "name": "Phạm Hữu Lầu",
        "description": "",
        "color": "#00A651",
        "line": "Tuyến số 4",
        "route": "Thạnh Xuân - Đại Lộ Nguyễn Văn Linh"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7175007,
          10.6943247
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "4",
        "name": "Cầu Bà Chiêm",
        "description": "",
        "color": "#00A651",
        "line": "Tuyến số 4",
        "route": "Thạnh Xuân - Đại Lộ Nguyễn Văn Linh"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.72324731135,
          10.672458692608
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "4",
        "name": "Long Thới",
        "description": "",
        "color": "#00A651",
        "line": "Tuyến số 4",
        "route": "Thạnh Xuân - Đại Lộ Nguyễn Văn Linh"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7276716,
          10.6562639
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "4",
        "name": "Hiệp Bình",
        "description": "",
        "color": "#00A651",
        "line": "Tuyến số 4",
        "route": "Thạnh Xuân - Đại Lộ Nguyễn Văn Linh"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7368127,
          10.6350489
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "5",
        "name": "Tân Cảng",
        "description": "",
        "color": "#8A1538",
        "line": "Tuyến số 5",
        "route": "Bến Xe Cần Giuộc mới - Cầu Sài Gòn"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7229938,
          10.7985298
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "5",
        "name": "Hàng Xanh",
        "description": "",
        "color": "#8A1538",
        "line": "Tuyến số 5",
        "route": "Bến Xe Cần Giuộc mới - Cầu Sài Gòn"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7115355,
          10.8011223
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "5",
        "name": "Bà Chiểu",
        "description": "",
        "color": "#8A1538",
        "line": "Tuyến số 5",
        "route": "Bến Xe Cần Giuộc mới - Cầu Sài Gòn"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.69866452528,
          10.802448709678
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "5",
        "name": "Nguyễn Văn Đậu",
        "description": "",
        "color": "#8A1538",
        "line": "Tuyến số 5",
        "route": "Bến Xe Cần Giuộc mới - Cầu Sài Gòn"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.686945,
          10.8034409
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "5",
        "name": "Ngã 4 Phú Nhuận",
        "description": "",
        "color": "#8A1538",
        "line": "Tuyến số 5",
        "route": "Bến Xe Cần Giuộc mới - Cầu Sài Gòn"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6803145,
          10.7998366
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "5",
        "name": "Hoàng Văn Thụ",
        "description": "",
        "color": "#8A1538",
        "line": "Tuyến số 5",
        "route": "Bến Xe Cần Giuộc mới - Cầu Sài Gòn"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.66662110702,
          10.800143892201
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "5",
        "name": "Lăng Cha Cả",
        "description": "",
        "color": "#8A1538",
        "line": "Tuyến số 5",
        "route": "Bến Xe Cần Giuộc mới - Cầu Sài Gòn"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6610463,
          10.8004538
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "5",
        "name": "Bảy Hiền",
        "description": "",
        "color": "#8A1538",
        "line": "Tuyến số 5",
        "route": "Bến Xe Cần Giuộc mới - Cầu Sài Gòn"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6528916,
          10.792765
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "5",
        "name": "Chợ Tân Bình",
        "description": "",
        "color": "#8A1538",
        "line": "Tuyến số 5",
        "route": "Bến Xe Cần Giuộc mới - Cầu Sài Gòn"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6528058,
          10.7858618
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "5",
        "name": "Bắc Hải",
        "description": "",
        "color": "#8A1538",
        "line": "Tuyến số 5",
        "route": "Bến Xe Cần Giuộc mới - Cầu Sài Gòn"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.656239,
          10.7785053
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "5",
        "name": "Bách Khoa",
        "description": "",
        "color": "#8A1538",
        "line": "Tuyến số 5",
        "route": "Bến Xe Cần Giuộc mới - Cầu Sài Gòn"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6582561,
          10.7711275
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "5",
        "name": "Phú Thọ",
        "description": "",
        "color": "#8A1538",
        "line": "Tuyến số 5",
        "route": "Bến Xe Cần Giuộc mới - Cầu Sài Gòn"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6593075,
          10.7648247
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "5",
        "name": "Đại Học Y Dược",
        "description": "",
        "color": "#8A1538",
        "line": "Tuyến số 5",
        "route": "Bến Xe Cần Giuộc mới - Cầu Sài Gòn"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.66283690078,
          10.755227443692
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "5",
        "name": "Xóm Củi",
        "description": "",
        "color": "#8A1538",
        "line": "Tuyến số 5",
        "route": "Bến Xe Cần Giuộc mới - Cầu Sài Gòn"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.66058550747,
          10.746464179585
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "5",
        "name": "Bến xe quận 8",
        "description": "",
        "color": "#8A1538",
        "line": "Tuyến số 5",
        "route": "Bến Xe Cần Giuộc mới - Cầu Sài Gòn"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6565181,
          10.733477
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "5",
        "name": "Bình Hưng",
        "description": "",
        "color": "#8A1538",
        "line": "Tuyến số 5",
        "route": "Bến Xe Cần Giuộc mới - Cầu Sài Gòn"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6548443,
          10.720743
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "5",
        "name": "Phong Phú",
        "description": "",
        "color": "#8A1538",
        "line": "Tuyến số 5",
        "route": "Bến Xe Cần Giuộc mới - Cầu Sài Gòn"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6548443,
          10.7024423
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "5",
        "name": "Trịnh Quang Nghị",
        "description": "",
        "color": "#8A1538",
        "line": "Tuyến số 5",
        "route": "Bến Xe Cần Giuộc mới - Cầu Sài Gòn"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6546726,
          10.6935867
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "5",
        "name": "Đa Phước",
        "description": "",
        "color": "#8A1538",
        "line": "Tuyến số 5",
        "route": "Bến Xe Cần Giuộc mới - Cầu Sài Gòn"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6517973,
          10.6680728
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "5",
        "name": "Bến xe Cần Giuộc",
        "description": "",
        "color": "#8A1538",
        "line": "Tuyến số 5",
        "route": "Bến Xe Cần Giuộc mới - Cầu Sài Gòn"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6718702,
          10.6043546
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "7",
        "name": "Bà Quẹo",
        "description": "",
        "color": "#F58220",
        "line": "Tuyến số 6",
        "route": "Bà Quẹo - Vòng xoay Phú Lâm"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6356396,
          10.8021973
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "7",
        "name": "Âu Cơ",
        "description": "",
        "color": "#F58220",
        "line": "Tuyến số 6",
        "route": "Bà Quẹo - Vòng xoay Phú Lâm"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.63779596693,
          10.796441082523
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "7",
        "name": "Thống Nhất",
        "description": "",
        "color": "#F58220",
        "line": "Tuyến số 6",
        "route": "Bà Quẹo - Vòng xoay Phú Lâm"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6371309,
          10.7901302
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "7",
        "name": "Công viên Tân Phú",
        "description": "",
        "color": "#F58220",
        "line": "Tuyến số 6",
        "route": "Bà Quẹo - Vòng xoay Phú Lâm"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.63639663226,
          10.783058715149
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "7",
        "name": "Hòa Bình",
        "description": "",
        "color": "#F58220",
        "line": "Tuyến số 6",
        "route": "Bà Quẹo - Vòng xoay Phú Lâm"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6320327145,
          10.769907574357
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "7",
        "name": "Đầm Sen",
        "description": "",
        "color": "#F58220",
        "line": "Tuyến số 6",
        "route": "Bà Quẹo - Vòng xoay Phú Lâm"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.632582,
          10.7635494
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "7",
        "name": "Phú Lâm",
        "description": "",
        "color": "#F58220",
        "line": "Tuyến số 6",
        "route": "Bà Quẹo - Vòng xoay Phú Lâm"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6344166,
          10.7539261
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "8",
        "name": "Thanh Đa",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến Monorail số 2",
        "route": "Quốc lộ 50 - Thanh Đa"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7451382,
          10.8183
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "8",
        "name": "Thảo Điền",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến Monorail số 2",
        "route": "Quốc lộ 50 - Thanh Đa"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7341089,
          10.800469
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "8",
        "name": "Bình An",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến Monorail số 2",
        "route": "Quốc lộ 50 - Thanh Đa"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7308259,
          10.7911736
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "8",
        "name": "Lương Định Của",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến Monorail số 2",
        "route": "Quốc lộ 50 - Thanh Đa"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7290235,
          10.7852295
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "8",
        "name": "Trần Não",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến Monorail số 2",
        "route": "Quốc lộ 50 - Thanh Đa"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7277146,
          10.7764396
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "8",
        "name": "Nam Thủ Thiêm",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến Monorail số 2",
        "route": "Quốc lộ 50 - Thanh Đa"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7270708,
          10.765436
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "8",
        "name": "Huỳnh Tấn Phát",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến Monorail số 2",
        "route": "Quốc lộ 50 - Thanh Đa"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.72770604639,
          10.754740940138
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "8",
        "name": "Tân Thuận Tây",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến Monorail số 2",
        "route": "Quốc lộ 50 - Thanh Đa"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7229295,
          10.749362
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "8",
        "name": "Nguyễn Thị Thập",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến Monorail số 2",
        "route": "Quốc lộ 50 - Thanh Đa"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7219639,
          10.7384523
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "8",
        "name": "Phú Mỹ Hưng",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến Monorail số 2",
        "route": "Quốc lộ 50 - Thanh Đa"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.71808725432,
          10.729200101577
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "8",
        "name": "Nguyễn Đức Cảnh",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến Monorail số 2",
        "route": "Quốc lộ 50 - Thanh Đa"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7091107,
          10.7280272
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "8",
        "name": "Nguyễn Hữu Thọ",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến Monorail số 2",
        "route": "Quốc lộ 50 - Thanh Đa"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7015362,
          10.7276582
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "8",
        "name": "RMIT",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến Monorail số 2",
        "route": "Quốc lộ 50 - Thanh Đa"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.694026,
          10.7276161
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "8",
        "name": "Cầu Ông Bé",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến Monorail số 2",
        "route": "Quốc lộ 50 - Thanh Đa"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6858187978,
          10.727726742385
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "8",
        "name": "Phạm Hùng",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến Monorail số 2",
        "route": "Quốc lộ 50 - Thanh Đa"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.67779061797,
          10.727513330541
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "8",
        "name": "Rạch Hiệp An",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến Monorail số 2",
        "route": "Quốc lộ 50 - Thanh Đa"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.66943707852,
          10.726374093345
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "8",
        "name": "Bình Hưng",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến Monorail số 2",
        "route": "Quốc lộ 50 - Thanh Đa"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6548443,
          10.720743
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "9",
        "name": "Công Ty Phần Mềm Quang Trung",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến Monorail số 3",
        "route": "Phan Văn Trị, Nguyễn Oanh - Tân Chánh H"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6280249,
          10.8517453
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "9",
        "name": "Phan Huy Ích",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến Monorail số 3",
        "route": "Phan Văn Trị, Nguyễn Oanh - Tân Chánh H"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6398444949,
          10.844183348796
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "9",
        "name": "Tân Sơn",
        "description": "On metro map as Nga Ba Phi Truong.",
        "color": "#00A0E2",
        "line": "Tuyến Monorail số 3",
        "route": "Phan Văn Trị, Nguyễn Oanh - Tân Chánh H"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6468942,
          10.8392281
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "9",
        "name": "Hạnh Thông Tây",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến Monorail số 3",
        "route": "Phan Văn Trị, Nguyễn Oanh - Tân Chánh H"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.65875938383,
          10.836047113761
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "9",
        "name": "Thống Nhất",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến Monorail số 3",
        "route": "Phan Văn Trị, Nguyễn Oanh - Tân Chánh H"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6643052539,
          10.834333920825
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "9",
        "name": "Xóm Thuốc",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến Monorail số 3",
        "route": "Phan Văn Trị, Nguyễn Oanh - Tân Chánh H"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.67130913872,
          10.829444762556
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "9",
        "name": "Ngã 6 Gò Vấp",
        "description": "",
        "color": "#00A0E2",
        "line": "Tuyến Monorail số 3",
        "route": "Phan Văn Trị, Nguyễn Oanh - Tân Chánh H"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6794991,
          10.8269833
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "134",
        "name": "Ga Thủ Thiêm",
        "description": "",
        "color": "#64748b",
        "line": "",
        "route": ""
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7494974018,
          10.787948726621
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "135",
        "name": "Sân bay Long Thành",
        "description": "",
        "color": "#64748b",
        "line": "",
        "route": ""
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          107.0001411,
          10.7407292
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "136",
        "name": "Biên Hòa",
        "description": "",
        "color": "#64748b",
        "line": "",
        "route": ""
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.8263579,
          10.9508209
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "137",
        "name": "Ga Dĩ An",
        "description": "",
        "color": "#64748b",
        "line": "",
        "route": ""
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7694363,
          10.907943
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "138",
        "name": "Vĩnh Phú",
        "description": "",
        "color": "#64748b",
        "line": "",
        "route": ""
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6997752,
          10.8775941
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "139",
        "name": "Thạnh Xuân",
        "description": "",
        "color": "#64748b",
        "line": "",
        "route": ""
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6665559503,
          10.874368377296
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "140",
        "name": "Tân Chánh Hiệp",
        "description": "",
        "color": "#64748b",
        "line": "",
        "route": ""
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6261831,
          10.866797
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "141",
        "name": "Vĩnh Lộc",
        "description": "",
        "color": "#64748b",
        "line": "",
        "route": ""
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.5977668,
          10.8122299
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "142",
        "name": "Ga Tân Kiên",
        "description": "",
        "color": "#64748b",
        "line": "",
        "route": ""
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.5839053,
          10.7162312
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "143",
        "name": "Tân An",
        "description": "",
        "color": "#64748b",
        "line": "",
        "route": ""
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.4077377,
          10.5360831
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "144",
        "name": "Ga Sài Gòn",
        "description": "",
        "color": "#64748b",
        "line": "",
        "route": ""
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6771786,
          10.7823643
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "145",
        "name": "Bình Triệu",
        "description": "",
        "color": "#64748b",
        "line": "",
        "route": ""
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7147219,
          10.8267094
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "146",
        "name": "Sóng Thần",
        "description": "",
        "color": "#64748b",
        "line": "",
        "route": ""
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.749773,
          10.8765493
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "10",
        "name": "Mê Linh",
        "description": "",
        "color": "#E4002B",
        "line": "Tuyến xe điện mặt đất số 1",
        "route": "Ba Son - Bến xe Miền Tây"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7062676,
          10.7752275
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "10",
        "name": "Calmet",
        "description": "",
        "color": "#E4002B",
        "line": "Tuyến xe điện mặt đất số 1",
        "route": "Ba Son - Bến xe Miền Tây"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7006572414,
          10.766539849774
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "10",
        "name": "Cầu Ông Lãnh",
        "description": "",
        "color": "#E4002B",
        "line": "Tuyến xe điện mặt đất số 1",
        "route": "Ba Son - Bến xe Miền Tây"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.69797832666,
          10.764439153899
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "10",
        "name": "Hồ Hảo Hớn",
        "description": "",
        "color": "#E4002B",
        "line": "Tuyến xe điện mặt đất số 1",
        "route": "Ba Son - Bến xe Miền Tây"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6934895,
          10.7597443
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "10",
        "name": "Nguyễn Cảnh Chân",
        "description": "",
        "color": "#E4002B",
        "line": "Tuyến xe điện mặt đất số 1",
        "route": "Ba Son - Bến xe Miền Tây"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.689713,
          10.7569406
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "10",
        "name": "Nguyễn Văn Cừ",
        "description": "",
        "color": "#E4002B",
        "line": "Tuyến xe điện mặt đất số 1",
        "route": "Ba Son - Bến xe Miền Tây"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6867733,
          10.7547271
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "10",
        "name": "Bệnh viện Nhiệt Đới",
        "description": "",
        "color": "#E4002B",
        "line": "Tuyến xe điện mặt đất số 1",
        "route": "Ba Son - Bến xe Miền Tây"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.677804,
          10.7527034
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "10",
        "name": "Đại Thế Giới",
        "description": "",
        "color": "#E4002B",
        "line": "Tuyến xe điện mặt đất số 1",
        "route": "Ba Son - Bến xe Miền Tây"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6696501,
          10.7506164
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "10",
        "name": "Tản Đà",
        "description": "",
        "color": "#E4002B",
        "line": "Tuyến xe điện mặt đất số 1",
        "route": "Ba Son - Bến xe Miền Tây"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6645002,
          10.7508483
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "10",
        "name": "Cầu Chà Và",
        "description": "",
        "color": "#E4002B",
        "line": "Tuyến xe điện mặt đất số 1",
        "route": "Ba Son - Bến xe Miền Tây"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.660552,
          10.7495201
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "10",
        "name": "Bình Tây",
        "description": "",
        "color": "#E4002B",
        "line": "Tuyến xe điện mặt đất số 1",
        "route": "Ba Son - Bến xe Miền Tây"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6519046,
          10.7452617
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "10",
        "name": "Bình Tiên",
        "description": "",
        "color": "#E4002B",
        "line": "Tuyến xe điện mặt đất số 1",
        "route": "Ba Son - Bến xe Miền Tây"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6438472,
          10.7405922
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "10",
        "name": "Lò Gốm",
        "description": "",
        "color": "#E4002B",
        "line": "Tuyến xe điện mặt đất số 1",
        "route": "Ba Son - Bến xe Miền Tây"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6352749,
          10.7354798
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "10",
        "name": "Phú Lâm D",
        "description": "",
        "color": "#E4002B",
        "line": "Tuyến xe điện mặt đất số 1",
        "route": "Ba Son - Bến xe Miền Tây"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.63146632425,
          10.737190823683
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "10",
        "name": "Chợ Bình Phú",
        "description": "",
        "color": "#E4002B",
        "line": "Tuyến xe điện mặt đất số 1",
        "route": "Ba Son - Bến xe Miền Tây"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6262197,
          10.7387686
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "10",
        "name": "An Dương Vương",
        "description": "",
        "color": "#E4002B",
        "line": "Tuyến xe điện mặt đất số 1",
        "route": "Ba Son - Bến xe Miền Tây"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.622411,
          10.7389899
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "10",
        "name": "Bến xe Miền Tây",
        "description": "",
        "color": "#E4002B",
        "line": "Tuyến xe điện mặt đất số 1",
        "route": "Ba Son - Bến xe Miền Tây"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.6190119,
          10.7410375
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "10",
        "name": "An Binh",
        "description": "",
        "color": "#E4002B",
        "line": "Tuyến xe điện mặt đất số 1",
        "route": "Ba Son - Bến xe Miền Tây"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.67330686703,
          10.749673031378
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "10",
        "name": "Cay Chu Y",
        "description": "",
        "color": "#E4002B",
        "line": "Tuyến xe điện mặt đất số 1",
        "route": "Ba Son - Bến xe Miền Tây"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.68411140459,
          10.752136368384
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "fid": "10",
        "name": "Ba Son",
        "description": "",
        "color": "#E4002B",
        "line": "Tuyến xe điện mặt đất số 1",
        "route": "Ba Son - Bến xe Miền Tây"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          106.7073727,
          10.7816039
        ]
      }
    }
  ]
} as GeoJSON.FeatureCollection;
}

export function metroPlanTodGeoJson(): GeoJSON.FeatureCollection {
  return {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "id": "5D16803E5B000003",
        "name": "KHU 5 - Tham Lương",
        "description": "- Nhà Ga chính: Ga & Depot Tham Lương\n- Diện tích 292,81 Ha\n\n+ Phạm vi ranh:\nPhía Đông: Giáp đường Tân Thới Nhất, đường số 22, đường số 17, ô phố dân cư hiện hữu và kênh Tham Lương;\nPhía Tây: Giáp kênh 19/5;\nPhía Nam: Giáp đường Lê Trọng Tấn; ô phố chức năng đất hỗn hợp và cây xanh, đất hạ tầng kỹ thuật, đất công trình dịch vụ công cộng và kênh Tham Lương;\nPhía Bắc: Giáp đường Phan Văn Hớn;"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              106.624488,
              10.82102
            ],
            [
              106.625014,
              10.821884
            ],
            [
              106.625126,
              10.82206
            ],
            [
              106.625167,
              10.822271
            ],
            [
              106.625151,
              10.822435
            ],
            [
              106.625099,
              10.822639
            ],
            [
              106.624696,
              10.823326
            ],
            [
              106.624497,
              10.823655
            ],
            [
              106.624416,
              10.823922
            ],
            [
              106.624311,
              10.824508
            ],
            [
              106.624062,
              10.825744
            ],
            [
              106.624001,
              10.82595
            ],
            [
              106.623772,
              10.826867
            ],
            [
              106.623674,
              10.827294
            ],
            [
              106.623383,
              10.827382
            ],
            [
              106.62127,
              10.82784
            ],
            [
              106.619264,
              10.828279
            ],
            [
              106.618246,
              10.828503
            ],
            [
              106.616242,
              10.829075
            ],
            [
              106.615332,
              10.82943
            ],
            [
              106.614383,
              10.829884
            ],
            [
              106.613295,
              10.830432
            ],
            [
              106.611998,
              10.831124
            ],
            [
              106.611927,
              10.831104
            ],
            [
              106.610036,
              10.827721
            ],
            [
              106.609126,
              10.826168
            ],
            [
              106.608611,
              10.82524
            ],
            [
              106.607898,
              10.823966
            ],
            [
              106.607772,
              10.823703
            ],
            [
              106.607645,
              10.823433
            ],
            [
              106.60741,
              10.823007
            ],
            [
              106.606536,
              10.821476
            ],
            [
              106.606549,
              10.821388
            ],
            [
              106.608656,
              10.819907
            ],
            [
              106.608719,
              10.819798
            ],
            [
              106.607551,
              10.818299
            ],
            [
              106.607806,
              10.818162
            ],
            [
              106.607305,
              10.817496
            ],
            [
              106.608305,
              10.816957
            ],
            [
              106.608075,
              10.816665
            ],
            [
              106.608306,
              10.816592
            ],
            [
              106.608165,
              10.81627
            ],
            [
              106.608003,
              10.816313
            ],
            [
              106.607783,
              10.815916
            ],
            [
              106.608625,
              10.815687
            ],
            [
              106.609597,
              10.815544
            ],
            [
              106.609762,
              10.81512
            ],
            [
              106.608729,
              10.814102
            ],
            [
              106.607601,
              10.813114
            ],
            [
              106.609343,
              10.812184
            ],
            [
              106.609846,
              10.812862
            ],
            [
              106.610159,
              10.812603
            ],
            [
              106.610815,
              10.813605
            ],
            [
              106.61122,
              10.813255
            ],
            [
              106.611296,
              10.813345
            ],
            [
              106.612329,
              10.812346
            ],
            [
              106.612406,
              10.812266
            ],
            [
              106.612469,
              10.812164
            ],
            [
              106.612416,
              10.812088
            ],
            [
              106.612813,
              10.811742
            ],
            [
              106.612813,
              10.811618
            ],
            [
              106.613223,
              10.811265
            ],
            [
              106.613797,
              10.811933
            ],
            [
              106.613987,
              10.811776
            ],
            [
              106.615405,
              10.810642
            ],
            [
              106.615456,
              10.810633
            ],
            [
              106.621487,
              10.817841
            ],
            [
              106.624488,
              10.82102
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "id": "5D16803E5C000004",
        "name": "KHU 4 - Tây tuyến/Logistics",
        "description": "- Nhà ga chính: Bà Quẹo, Phạm Văn Bạch, Tây Thạnh\n- Diện tích: 148,92 Ha\n\n+ Phạm vi ranh:\nPhía Đông: Giáp ô phố chức năng đất ở, đường Trường Chinh, khu vực sân bay Tân Sơn Nhất, đường Phạm Văn Bạch, đường Trần Thái Tông, đường Phan Huy Ích;\nPhía Tây: Giáp ô phố chức năng đất công nghiệp, đất ở và đường Tây Thạnh, đường CN2, đường D15, đường D10, đường D16, đường D9, đường Chế Lan Viên, đường hẻm 71, đường Lê Trọng Tấn;\nPhía Nam: Giáp ô phố chức năng đất ở, đất công trình dịch vụ công cộng và đường Tân Kỳ Tân Quý;\nPhía Bắc: Giáp khu công nghiệp, đường CN5;"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              106.632513,
              10.815417
            ],
            [
              106.632004,
              10.815299
            ],
            [
              106.631957,
              10.815288
            ],
            [
              106.630604,
              10.819763
            ],
            [
              106.631112,
              10.819944
            ],
            [
              106.632482,
              10.819119
            ],
            [
              106.632552,
              10.819155
            ],
            [
              106.632546,
              10.819319
            ],
            [
              106.632512,
              10.819756
            ],
            [
              106.63251,
              10.820003
            ],
            [
              106.632558,
              10.820384
            ],
            [
              106.632579,
              10.820532
            ],
            [
              106.6325,
              10.820758
            ],
            [
              106.632436,
              10.820885
            ],
            [
              106.632535,
              10.820896
            ],
            [
              106.632742,
              10.820994
            ],
            [
              106.633225,
              10.821232
            ],
            [
              106.633344,
              10.821181
            ],
            [
              106.633459,
              10.821143
            ],
            [
              106.634122,
              10.82149
            ],
            [
              106.634136,
              10.821541
            ],
            [
              106.63384,
              10.822055
            ],
            [
              106.633796,
              10.822073
            ],
            [
              106.63369,
              10.822028
            ],
            [
              106.633554,
              10.822019
            ],
            [
              106.633344,
              10.822097
            ],
            [
              106.633019,
              10.82218
            ],
            [
              106.632493,
              10.822296
            ],
            [
              106.63229,
              10.82247
            ],
            [
              106.632189,
              10.822643
            ],
            [
              106.632349,
              10.822736
            ],
            [
              106.632425,
              10.82288
            ],
            [
              106.632483,
              10.823185
            ],
            [
              106.632124,
              10.82388
            ],
            [
              106.631766,
              10.823679
            ],
            [
              106.631705,
              10.823701
            ],
            [
              106.631558,
              10.823913
            ],
            [
              106.631341,
              10.824188
            ],
            [
              106.631002,
              10.824664
            ],
            [
              106.630696,
              10.824949
            ],
            [
              106.63065,
              10.824945
            ],
            [
              106.630336,
              10.824269
            ],
            [
              106.630096,
              10.824472
            ],
            [
              106.629383,
              10.825165
            ],
            [
              106.628978,
              10.825448
            ],
            [
              106.628915,
              10.825442
            ],
            [
              106.62793,
              10.824258
            ],
            [
              106.626725,
              10.822834
            ],
            [
              106.62655,
              10.822627
            ],
            [
              106.625532,
              10.821253
            ],
            [
              106.625192,
              10.820794
            ],
            [
              106.622245,
              10.817507
            ],
            [
              106.622252,
              10.817454
            ],
            [
              106.623199,
              10.816611
            ],
            [
              106.623351,
              10.816456
            ],
            [
              106.624449,
              10.815487
            ],
            [
              106.624534,
              10.815487
            ],
            [
              106.625978,
              10.81688
            ],
            [
              106.626201,
              10.816674
            ],
            [
              106.62669,
              10.815989
            ],
            [
              106.626854,
              10.816084
            ],
            [
              106.627488,
              10.81469
            ],
            [
              106.627339,
              10.814615
            ],
            [
              106.627391,
              10.81449
            ],
            [
              106.626784,
              10.814228
            ],
            [
              106.62593,
              10.813594
            ],
            [
              106.625923,
              10.81356
            ],
            [
              106.627269,
              10.811662
            ],
            [
              106.627449,
              10.811491
            ],
            [
              106.627052,
              10.811313
            ],
            [
              106.627115,
              10.81025
            ],
            [
              106.627159,
              10.810211
            ],
            [
              106.627591,
              10.81024
            ],
            [
              106.627801,
              10.810301
            ],
            [
              106.628653,
              10.810355
            ],
            [
              106.62887,
              10.81036
            ],
            [
              106.629241,
              10.810351
            ],
            [
              106.629467,
              10.810348
            ],
            [
              106.630392,
              10.810425
            ],
            [
              106.630617,
              10.810449
            ],
            [
              106.631105,
              10.809489
            ],
            [
              106.631212,
              10.809313
            ],
            [
              106.631343,
              10.809007
            ],
            [
              106.6314,
              10.808807
            ],
            [
              106.631452,
              10.808562
            ],
            [
              106.631466,
              10.808356
            ],
            [
              106.631449,
              10.807982
            ],
            [
              106.631414,
              10.807631
            ],
            [
              106.63119,
              10.805602
            ],
            [
              106.632082,
              10.804554
            ],
            [
              106.632791,
              10.80367
            ],
            [
              106.63287,
              10.803639
            ],
            [
              106.633986,
              10.803807
            ],
            [
              106.6354,
              10.803953
            ],
            [
              106.636027,
              10.804038
            ],
            [
              106.636616,
              10.804087
            ],
            [
              106.637288,
              10.804325
            ],
            [
              106.637162,
              10.8045
            ],
            [
              106.636667,
              10.805199
            ],
            [
              106.636192,
              10.805825
            ],
            [
              106.635913,
              10.806146
            ],
            [
              106.635859,
              10.806239
            ],
            [
              106.635562,
              10.806587
            ],
            [
              106.635378,
              10.806827
            ],
            [
              106.635255,
              10.806986
            ],
            [
              106.635131,
              10.807451
            ],
            [
              106.634315,
              10.80958
            ],
            [
              106.634316,
              10.809648
            ],
            [
              106.632513,
              10.815417
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "id": "5D16803E5C000005",
        "name": "KHU 3 - Nguyễn Hồng Đào",
        "description": "- Nhà Ga chính: Nguyễn Hồng Đào\n- Diện tích: 43,81 Ha\n\n+ Phạm vi ranh:\nPhía Bắc: Giáp đường Cộng Hòa và đường Đồng Xoài;\nĐông: Giáp đường Trường Chinh, giáp đường Hoàng Hoa Thám, đường Đồng Đen;\nPhía Tây: Giáp đường Trương Công Định, đường Ấp Bắc;\nPhía Nam: Giáp đường Bàu Cát;"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              106.647162,
              10.799485
            ],
            [
              106.647151,
              10.799523
            ],
            [
              106.646549,
              10.800141
            ],
            [
              106.646432,
              10.800259
            ],
            [
              106.645207,
              10.80155
            ],
            [
              106.644974,
              10.801695
            ],
            [
              106.644998,
              10.801896
            ],
            [
              106.644952,
              10.801942
            ],
            [
              106.641771,
              10.802205
            ],
            [
              106.641735,
              10.802186
            ],
            [
              106.641645,
              10.80159
            ],
            [
              106.641494,
              10.800568
            ],
            [
              106.641551,
              10.800274
            ],
            [
              106.641665,
              10.800165
            ],
            [
              106.641306,
              10.799586
            ],
            [
              106.641321,
              10.799525
            ],
            [
              106.642071,
              10.799127
            ],
            [
              106.642055,
              10.799088
            ],
            [
              106.641953,
              10.798761
            ],
            [
              106.641293,
              10.796713
            ],
            [
              106.640882,
              10.795472
            ],
            [
              106.640807,
              10.795209
            ],
            [
              106.640819,
              10.795178
            ],
            [
              106.642776,
              10.794397
            ],
            [
              106.644634,
              10.793656
            ],
            [
              106.644671,
              10.793648
            ],
            [
              106.645228,
              10.795265
            ],
            [
              106.645729,
              10.796715
            ],
            [
              106.64584,
              10.797083
            ],
            [
              106.646838,
              10.796612
            ],
            [
              106.646912,
              10.796654
            ],
            [
              106.647162,
              10.799485
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "id": "5D16803E5C000006",
        "name": "KHU 2 - Trục CMT8/Hòa Hưng/Bảy Hiền",
        "description": "- Nhà ga chính: Dân Chủ, Hòa Hưng, Lê Thị Riêng, Phạm Văn Hai, Bảy Hiền\n\n- Diện tích: 265,07 Ha\n\n- Phạm vi ranh:\n+ Phía Bắc: Giáp đường Hoàng Văn Thụ, đường Xuân Diệu, đường Nguyễn Thái Bình;\n+ Phía Đông: Giáp kênh Nhiêu Lộc, đường Hoàng Sa, đường Trường Sa, đường Bà Huyện Thanh Quan, đường Lý Chính Thắng, đường Điện Biên Phủ;\n+ Phía Tây: Giáp đường Tô Hiến Thành, đường Hồ Bá Kiện, công viên Lê Thị Riêng, đường Bành Văn Trân, đường Năm Châu;\n+ Phía Nam: Giáp đường Cách Mạng Tháng Tám, đường Hòa Hưng;"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              106.680232,
              10.783908
            ],
            [
              106.680206,
              10.783981
            ],
            [
              106.679383,
              10.783958
            ],
            [
              106.679236,
              10.783912
            ],
            [
              106.679085,
              10.783851
            ],
            [
              106.678843,
              10.783792
            ],
            [
              106.678616,
              10.783828
            ],
            [
              106.678349,
              10.783787
            ],
            [
              106.678098,
              10.783862
            ],
            [
              106.677905,
              10.783999
            ],
            [
              106.677788,
              10.784132
            ],
            [
              106.677659,
              10.784239
            ],
            [
              106.677544,
              10.784305
            ],
            [
              106.677223,
              10.784434
            ],
            [
              106.676755,
              10.784607
            ],
            [
              106.676317,
              10.784818
            ],
            [
              106.676101,
              10.784991
            ],
            [
              106.675822,
              10.785189
            ],
            [
              106.675661,
              10.785298
            ],
            [
              106.675121,
              10.785746
            ],
            [
              106.674618,
              10.7862
            ],
            [
              106.67434,
              10.786415
            ],
            [
              106.674181,
              10.786509
            ],
            [
              106.673989,
              10.786597
            ],
            [
              106.673365,
              10.786782
            ],
            [
              106.671783,
              10.787276
            ],
            [
              106.670253,
              10.787742
            ],
            [
              106.668852,
              10.78822
            ],
            [
              106.668154,
              10.788481
            ],
            [
              106.667852,
              10.788599
            ],
            [
              106.667513,
              10.788773
            ],
            [
              106.667119,
              10.788954
            ],
            [
              106.666716,
              10.789154
            ],
            [
              106.666527,
              10.789256
            ],
            [
              106.666422,
              10.78938
            ],
            [
              106.666354,
              10.78957
            ],
            [
              106.666355,
              10.789707
            ],
            [
              106.666386,
              10.789883
            ],
            [
              106.666441,
              10.789994
            ],
            [
              106.666427,
              10.790134
            ],
            [
              106.666367,
              10.790234
            ],
            [
              106.666269,
              10.790328
            ],
            [
              106.666075,
              10.790406
            ],
            [
              106.665965,
              10.790477
            ],
            [
              106.665859,
              10.790514
            ],
            [
              106.665706,
              10.790527
            ],
            [
              106.665487,
              10.790543
            ],
            [
              106.665336,
              10.790594
            ],
            [
              106.664428,
              10.790951
            ],
            [
              106.664094,
              10.791072
            ],
            [
              106.663673,
              10.791231
            ],
            [
              106.663449,
              10.791309
            ],
            [
              106.663203,
              10.791346
            ],
            [
              106.662863,
              10.791382
            ],
            [
              106.662089,
              10.79136
            ],
            [
              106.662061,
              10.791328
            ],
            [
              106.661863,
              10.791404
            ],
            [
              106.661168,
              10.791653
            ],
            [
              106.660859,
              10.791774
            ],
            [
              106.66065,
              10.791928
            ],
            [
              106.660524,
              10.792021
            ],
            [
              106.660053,
              10.792375
            ],
            [
              106.659898,
              10.792512
            ],
            [
              106.659791,
              10.792593
            ],
            [
              106.659208,
              10.793028
            ],
            [
              106.659019,
              10.793194
            ],
            [
              106.659035,
              10.793347
            ],
            [
              106.659122,
              10.793538
            ],
            [
              106.659285,
              10.793661
            ],
            [
              106.65928,
              10.793775
            ],
            [
              106.659275,
              10.793919
            ],
            [
              106.659428,
              10.794119
            ],
            [
              106.659595,
              10.794504
            ],
            [
              106.659994,
              10.794925
            ],
            [
              106.660177,
              10.795363
            ],
            [
              106.660127,
              10.795588
            ],
            [
              106.660215,
              10.795648
            ],
            [
              106.660131,
              10.795905
            ],
            [
              106.661011,
              10.796309
            ],
            [
              106.660917,
              10.796618
            ],
            [
              106.660813,
              10.796653
            ],
            [
              106.660785,
              10.796771
            ],
            [
              106.660575,
              10.797048
            ],
            [
              106.659932,
              10.798103
            ],
            [
              106.65984,
              10.798267
            ],
            [
              106.659418,
              10.798634
            ],
            [
              106.659365,
              10.798652
            ],
            [
              106.658748,
              10.798037
            ],
            [
              106.658323,
              10.797618
            ],
            [
              106.656538,
              10.795913
            ],
            [
              106.655829,
              10.795235
            ],
            [
              106.655577,
              10.795465
            ],
            [
              106.654694,
              10.796345
            ],
            [
              106.654482,
              10.796561
            ],
            [
              106.654193,
              10.79685
            ],
            [
              106.654131,
              10.79686
            ],
            [
              106.653765,
              10.796646
            ],
            [
              106.653567,
              10.796583
            ],
            [
              106.65332,
              10.796541
            ],
            [
              106.652982,
              10.796532
            ],
            [
              106.652699,
              10.79653
            ],
            [
              106.652586,
              10.796508
            ],
            [
              106.652502,
              10.796448
            ],
            [
              106.652355,
              10.796377
            ],
            [
              106.651671,
              10.796008
            ],
            [
              106.651479,
              10.795903
            ],
            [
              106.65065,
              10.795443
            ],
            [
              106.650356,
              10.794833
            ],
            [
              106.650352,
              10.794774
            ],
            [
              106.650398,
              10.794698
            ],
            [
              106.650458,
              10.794672
            ],
            [
              106.650328,
              10.794333
            ],
            [
              106.650086,
              10.793831
            ],
            [
              106.650071,
              10.793794
            ],
            [
              106.650089,
              10.793764
            ],
            [
              106.650148,
              10.793734
            ],
            [
              106.650203,
              10.793707
            ],
            [
              106.650192,
              10.793632
            ],
            [
              106.649732,
              10.792801
            ],
            [
              106.649659,
              10.792632
            ],
            [
              106.649661,
              10.792584
            ],
            [
              106.649721,
              10.79223
            ],
            [
              106.649777,
              10.791928
            ],
            [
              106.649887,
              10.791347
            ],
            [
              106.649957,
              10.791149
            ],
            [
              106.649996,
              10.791038
            ],
            [
              106.650184,
              10.790767
            ],
            [
              106.650415,
              10.790443
            ],
            [
              106.650359,
              10.790378
            ],
            [
              106.6504,
              10.79033
            ],
            [
              106.65118,
              10.789701
            ],
            [
              106.65165,
              10.789481
            ],
            [
              106.651796,
              10.789393
            ],
            [
              106.651939,
              10.789637
            ],
            [
              106.651982,
              10.789568
            ],
            [
              106.651917,
              10.789353
            ],
            [
              106.652215,
              10.789393
            ],
            [
              106.652618,
              10.789502
            ],
            [
              106.652887,
              10.78957
            ],
            [
              106.652976,
              10.789207
            ],
            [
              106.653242,
              10.788295
            ],
            [
              106.65329,
              10.788275
            ],
            [
              106.65378,
              10.788306
            ],
            [
              106.653855,
              10.788331
            ],
            [
              106.654449,
              10.788822
            ],
            [
              106.655054,
              10.789314
            ],
            [
              106.655314,
              10.789477
            ],
            [
              106.656101,
              10.788855
            ],
            [
              106.656292,
              10.788696
            ],
            [
              106.656554,
              10.788421
            ],
            [
              106.656722,
              10.788352
            ],
            [
              106.659079,
              10.788414
            ],
            [
              106.660294,
              10.788397
            ],
            [
              106.66154,
              10.788345
            ],
            [
              106.661722,
              10.788355
            ],
            [
              106.662076,
              10.788164
            ],
            [
              106.66185,
              10.787856
            ],
            [
              106.661707,
              10.787713
            ],
            [
              106.66147,
              10.787466
            ],
            [
              106.661381,
              10.787485
            ],
            [
              106.661346,
              10.787465
            ],
            [
              106.660969,
              10.787036
            ],
            [
              106.660629,
              10.786623
            ],
            [
              106.660497,
              10.78649
            ],
            [
              106.660277,
              10.78638
            ],
            [
              106.660168,
              10.786369
            ],
            [
              106.660072,
              10.786314
            ],
            [
              106.659992,
              10.786224
            ],
            [
              106.659958,
              10.786114
            ],
            [
              106.659916,
              10.785894
            ],
            [
              106.660183,
              10.785807
            ],
            [
              106.66031,
              10.785807
            ],
            [
              106.660364,
              10.785815
            ],
            [
              106.660499,
              10.785824
            ],
            [
              106.660698,
              10.785842
            ],
            [
              106.660802,
              10.785783
            ],
            [
              106.661585,
              10.785339
            ],
            [
              106.661703,
              10.785234
            ],
            [
              106.662104,
              10.785078
            ],
            [
              106.662172,
              10.785086
            ],
            [
              106.662279,
              10.784954
            ],
            [
              106.662472,
              10.784779
            ],
            [
              106.662739,
              10.784539
            ],
            [
              106.663082,
              10.784301
            ],
            [
              106.66329,
              10.784199
            ],
            [
              106.66334,
              10.784167
            ],
            [
              106.664333,
              10.783612
            ],
            [
              106.665024,
              10.783232
            ],
            [
              106.665216,
              10.783123
            ],
            [
              106.664725,
              10.782295
            ],
            [
              106.664747,
              10.782234
            ],
            [
              106.665358,
              10.781899
            ],
            [
              106.666191,
              10.783396
            ],
            [
              106.666733,
              10.782933
            ],
            [
              106.666944,
              10.782751
            ],
            [
              106.667314,
              10.782447
            ],
            [
              106.669343,
              10.781019
            ],
            [
              106.669398,
              10.781014
            ],
            [
              106.669681,
              10.781226
            ],
            [
              106.669824,
              10.780934
            ],
            [
              106.670146,
              10.780199
            ],
            [
              106.671042,
              10.778092
            ],
            [
              106.671106,
              10.778066
            ],
            [
              106.676798,
              10.780181
            ],
            [
              106.677233,
              10.780346
            ],
            [
              106.678659,
              10.779583
            ],
            [
              106.678846,
              10.77949
            ],
            [
              106.680104,
              10.778811
            ],
            [
              106.679951,
              10.778534
            ],
            [
              106.679408,
              10.77755
            ],
            [
              106.680378,
              10.777011
            ],
            [
              106.679715,
              10.775864
            ],
            [
              106.679903,
              10.775765
            ],
            [
              106.680156,
              10.775442
            ],
            [
              106.680399,
              10.775027
            ],
            [
              106.680572,
              10.774853
            ],
            [
              106.680875,
              10.774535
            ],
            [
              106.680936,
              10.774534
            ],
            [
              106.682544,
              10.775891
            ],
            [
              106.683394,
              10.776615
            ],
            [
              106.683743,
              10.77694
            ],
            [
              106.684658,
              10.777802
            ],
            [
              106.684652,
              10.777856
            ],
            [
              106.683779,
              10.778361
            ],
            [
              106.683161,
              10.778719
            ],
            [
              106.682749,
              10.77892
            ],
            [
              106.681932,
              10.77932
            ],
            [
              106.682553,
              10.780653
            ],
            [
              106.682654,
              10.780883
            ],
            [
              106.682643,
              10.780961
            ],
            [
              106.6801,
              10.782543
            ],
            [
              106.680232,
              10.783908
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "id": "5D16803E5D000007",
        "name": "KHU 1 - Trung Tâm",
        "description": "- Nhà Ga chính: Bến Thành, Tao Đàn\n- Diện Tích 188,57 Ha\n\n+ Phạm vi ranh:\nPhía Bắc: Giáp các tuyến Trương Định, Nam Kỳ Khởi Nghĩa, Nguyễn Trung Trực và Lý Tự Trọng.\nPhía Đông: Giáp Sông Sài Gòn, các tuyến Nam Kỳ Khởi Nghĩa, Bến Vân Đồn, Võ Văn Kiệt và Rạch Bến Nghé.\nPhía Tây: Giáp các tuyến Nguyễn Đình Chiểu, Hồ Bá Kiện, Nguyễn Thị Minh Khai, Lương Hữu Khánh, Bùi Thị Xuân và Nguyễn Trãi.\nPhía Nam: Giáp các tuyến Nguyễn Cư Trinh, Cống Quỳnh, Trần Hưng Đạo và Nguyễn Thái Học."
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              106.701296,
              10.770398
            ],
            [
              106.700903,
              10.771307
            ],
            [
              106.700273,
              10.772766
            ],
            [
              106.699976,
              10.773147
            ],
            [
              106.699684,
              10.773354
            ],
            [
              106.698851,
              10.774083
            ],
            [
              106.698164,
              10.774684
            ],
            [
              106.698081,
              10.77466
            ],
            [
              106.69774,
              10.774319
            ],
            [
              106.697051,
              10.773842
            ],
            [
              106.695422,
              10.77271
            ],
            [
              106.694515,
              10.773467
            ],
            [
              106.694281,
              10.773696
            ],
            [
              106.691777,
              10.775804
            ],
            [
              106.689623,
              10.777746
            ],
            [
              106.689519,
              10.777742
            ],
            [
              106.68705,
              10.775131
            ],
            [
              106.686736,
              10.7748
            ],
            [
              106.685936,
              10.773956
            ],
            [
              106.687261,
              10.773143
            ],
            [
              106.686926,
              10.772778
            ],
            [
              106.687433,
              10.772306
            ],
            [
              106.687738,
              10.772081
            ],
            [
              106.687972,
              10.771865
            ],
            [
              106.686297,
              10.770085
            ],
            [
              106.686307,
              10.769989
            ],
            [
              106.68768,
              10.768965
            ],
            [
              106.686425,
              10.767676
            ],
            [
              106.688163,
              10.766819
            ],
            [
              106.688309,
              10.767111
            ],
            [
              106.688513,
              10.767012
            ],
            [
              106.688642,
              10.766679
            ],
            [
              106.688493,
              10.766502
            ],
            [
              106.68841,
              10.7665
            ],
            [
              106.688225,
              10.766374
            ],
            [
              106.688028,
              10.765817
            ],
            [
              106.687178,
              10.763413
            ],
            [
              106.687201,
              10.763345
            ],
            [
              106.689712,
              10.761779
            ],
            [
              106.692105,
              10.764529
            ],
            [
              106.692597,
              10.764505
            ],
            [
              106.694024,
              10.762486
            ],
            [
              106.695673,
              10.763899
            ],
            [
              106.696263,
              10.762896
            ],
            [
              106.69662,
              10.762543
            ],
            [
              106.697651,
              10.763806
            ],
            [
              106.697999,
              10.764237
            ],
            [
              106.69988,
              10.765414
            ],
            [
              106.70016,
              10.76559
            ],
            [
              106.700544,
              10.765832
            ],
            [
              106.700854,
              10.766284
            ],
            [
              106.701222,
              10.767072
            ],
            [
              106.701417,
              10.767307
            ],
            [
              106.702168,
              10.768217
            ],
            [
              106.702186,
              10.768339
            ],
            [
              106.701296,
              10.770398
            ]
          ]
        ]
      }
    }
  ]
} as GeoJSON.FeatureCollection;
}
